### ISSUE TITLE
Layout and align cannot be used together with responsive API

### ISSUE THREAD

**Issue by aeslinger0** [philmtd/css-fx-layout#20]
Great project! It solved a layout thrashing performance problem that the flex-layout causes when too many elements are on the page. I've experienced that problem on various projects for **years** and only realized that it was flex-layout itself that was causing it after I switched to this. From >20sec page load to <2sec. So thank you for this.

I have a div that looks like this:

```<div data-layout-gt-xs="row" data-layout-xs="column" data-layout-align="start">```

It should switch from `row` to `column` layout  on xs screens, but this style is preventing it:

```
	*[data-layout-align]:not([data-layout]) {
		@include flex-row-properties;
	}
```

I believe the intention was to add the display, flex-direction, and flex-wrap styles if _only_ the data-layout-align attribute was used, but the `:not([data-layout])` part isn't matching because I have "-gt-xs" and "-xs"  appended to the `data-layout` attributes.

I think you need to add variations in the `:not()` portion for all the breakpoints.

**Comment by philmtd** [comment]
Hi @aeslinger0, thank you for this bug report. 

I can confirm this does not work as expected and desired.

It works using class selectors, by the way, because the allegedly same rule looks like this:

```html
<div class="fx-layout-row--gt-xs fx-layout-column--xs fx-align--start-x">
```

```scss
*[class*="fx-align--"]:not([class*="fx-layout"]) {
  @include flex-row-properties;
}
```

Here we test "all elements which contain `fx-align--` in their classes string but don't contain `fx-layout`". The attribute version cannot do this because we'd need to test whether the element contains attributes starting with the names `data-layout-align` or `data-layout`. That is not possible in CSS I'm afraid because the "contains" check is possible only for attribute values, not for attribute names.

Fortunately making the attribute version a little more verbose should do the trick:

```scss
*[data-layout-align]:not([data-layout],[data-layout-xs],[data-layout-sm],[data-layout-md],[data-layout-lg],[data-layout-xl],[data-layout-lt-sm],[data-layout-lt-md],[data-layout-lt-lg],[data-layout-lt-xl],[data-layout-gt-xs],[data-layout-gt-sm],[data-layout-gt-md],[data-layout-gt-lg]) {
	@include flex-row-properties;
}
```

I'll fix this in a few minutes.

**Comment by philmtd** [comment]
Thanks again. I just released it in [3.0.1](https://www.npmjs.com/package/css-fx-layout/v/3.0.1).

**Comment by aeslinger0** [comment]
Thanks for responding so quickly! I think this problem would anywhere there is a `:not([data-layout])`, wouldn't it? I did a search through the code and found some other instances that I think would have the same problem:

https://github.com/philmtd/css-fx-layout/search?q=not%28%5Bdata-layout%5D

**Comment by philmtd** [comment]
Yes indeed, thanks for the code review! ;) I'm going to fix this, too.

**Comment by philmtd** [comment]
Done: [3.0.2](https://www.npmjs.com/package/css-fx-layout/v/3.0.2)
