### ISSUE TITLE
Using css-fx with sveltekit

### ISSUE THREAD

**Issue by st-clair-clarke** [philmtd/css-fx-layout#36]
svletekit use a global css file name app.css.

Placing fx mixin in it generate errors. Is there a way to use the following in a .css file:

```
@use "css-fx-layout" as fx;

// If you want to include the responsive API selectors
$includeResponsiveApi: true;

// If you choose to use CSS class selectors:
@include fx.class-selectors($includeResponsiveApi);
@include fx.gap-class-selectors(1, 16, 1, px em, $includeResponsiveApi);
@include fx.gap-class-selectors-from-list(32 48, px em, $includeResponsiveApi);
@include fx.flex-size-class-selectors(5, 100, 5, $includeResponsiveApi);
@include fx.flex-size-class-selectors-from-list(33 66, $includeResponsiveApi);
```

**Comment by philmtd** [comment]
Hi @st-clair-clarke, this is a SCSS library. You cannot use it in plain CSS.

See if you can change your project to use SCSS. This should natively be possible in SvelteKit apps (https://svelte.dev/docs/kit/integrations#vitePreprocess).

Alternatively, you could try to compile the SCSS code into a CSS file and include that in your project. Effectively, you'd not be using this as an npm dependency then.

I'd recommend updating your project to use SCSS instead of CSS as this is a good idea anyway, in my opinion.

Does this help you?

**Comment by st-clair-clarke** [comment]
It did. Thanks.
